spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database : postgresql
    database-platform : org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
  http:
    encoding:
      charset : UTF-8
      enabled : true
      force : true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: grumbla@gmail.com
    password: password
    port: 587
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com

server:
  port : 8888
  tomcat:
    uri-encoding: UTF-8
blog:
  title : DevPub
  subtitle : Рассказы разработчиков
  phone : +7 922 000-00-00
  email : grumbla@mail.ru
  copyright : Виктория Горячева
  copyrightFrom : 2005
upload:
  path: upload
